// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ceG3X7619XQzTUj_2S0VkUVs8wS4MhA',
    appId: '1:292995348302:web:58ae877278ffe29e1b101f',
    messagingSenderId: '292995348302',
    projectId: 'anboba',
    authDomain: 'anboba.firebaseapp.com',
    storageBucket: 'anboba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0dsQNuxb6tRzI_6mTo9ErJ4smqdanp8',
    appId: '1:292995348302:android:79dc538d2b96c3df1b101f',
    messagingSenderId: '292995348302',
    projectId: 'anboba',
    storageBucket: 'anboba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABhqWhOFiaaapbKe45ZUoig9-6tw7LOOk',
    appId: '1:292995348302:ios:df313057250419f71b101f',
    messagingSenderId: '292995348302',
    projectId: 'anboba',
    storageBucket: 'anboba.appspot.com',
    iosClientId:
        '292995348302-t8g24kjmcq264tfkq082pio7ig1fl0i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.anboba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABhqWhOFiaaapbKe45ZUoig9-6tw7LOOk',
    appId: '1:292995348302:ios:df313057250419f71b101f',
    messagingSenderId: '292995348302',
    projectId: 'anboba',
    storageBucket: 'anboba.appspot.com',
    iosClientId:
        '292995348302-t8g24kjmcq264tfkq082pio7ig1fl0i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.anboba',
  );
}
